# Generated by Django 3.1.7 on 2021-06-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lastDate',
            field=models.DateField(default='2001-04-12'),
        ),
    ]
