# Generated by Django 3.1.7 on 2021-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
